NICKNAMES = {
    "Бесу": "Bes",
    "Боров": "Borov",
    "Клыке": "Fang",
    "Призрака": "Ghost",
    "Призраке": "Ghost",
    "Меченый": "Marked",
    "Меченным": "Marked One",
    "Меченный": "Marked One",
    "Стрелка": "Strelok",
    "Стрелок": "Strelok",
    "Стрелком": "Strelok",
    "Неумёх": "Clumsy",
    "Неумеха": "Clumsy",
    "Фанат": "Fanatic",
    "Лис": "Fox",
    "Рыжего": "Red",
    "Рыжему": "Red",
    "Долговязый": "Longshanks",
}

GLOSSARY = {
    "«": "REPL_GUILLL",
    "»": "REPL_GUILLR",
    # Zone - General
    "выброса": "emission",
    "выброс": "blowout",
    # Anomalies - Special
    "Мозговыжигатель": "Brain Scorcher",
    # Anomalies - General
    "Плешь": "Bald Spot",
    "Жарка": "Burner",
    "жарки": "Burner",
    "Жгучий пух": "Burnt Fuzz",
    "Электра": "Electro",
    "электры": "Electro",
    "Кисель": "Fruit Punch",
    "киселя": "Fruit Punch",
    "Холодец": "Chiller",
    "холодца": "Chiller",
    "Лифт": "Lift",
    "Трамплин": "Springboard",
    "Кровь камня": "Stone Blood",
    "Воронка": "Vortex",
    "воронки": "Vortex",
    "Карусель": "Whirligig",
    "карусели": "Whirligig",
    # Artifacts
    "Пустышка": "Bubble",
    "Кристальная колючка": "Crystal Thorn",
    "Капли": "Droplets",
    "Капля": "Droplets",
    "Электробусы": "Electric Bus",
    "Грави": "Gravi",
    "Прыгалка": "Jump Rope",
    "Мамины бусы": "Mama's Beads",
    "Бабкины бусы": "Granny's Beads",
    "Бусы прабабки": "Great-Granny's Beads",
    "Бусы бабки бюрера": "Burer's Granny's Beads",
    "Ломоть мяса": "Meat Chunk",
    "Колючка": "Thorn",
    "Морской ёж": "Urchin",
    "Дирижабль": "Zeppelin",
    # Factions
    "Чистое Небо": "Clear Sky",
    "Долг": "Duty",
    "Долговцы": "Duty",
    "Свобода": "Freedom",
    "Свободовцы": "Freedom",
    "Монолитовцы": "Monolith",
    # Regions
    "Кордон": "Cordon",
    "Райцентре": "District Center",
    "Забытый хутор": "Forgotten Hamlet",
    "Свалки": "Garbage",
    "Свалку": "Garbage",
    "Свалка": "Garbage",
    "Кишке": "Gut",
    "Кишки": "Gut",
    "Рыжий лес": "Red Forest",
    "Дикую территорию": "Wild Territory",
    "Янтарь": "Yantar",
    "100 Рентген": "100 Rads",
    # Mutants
    "бюрера": "Burer",
    "Бюрер": "Burer",
    # Other
    "Лешего": "Woodsman",
}

GLOSSARY_DEEPL = {
    # Equipment
    "ПДА": "PDA",
    "Боеприпасы:": "Ammunition:",
    # Factions - Derivatives
    "долгівці": "Duty members",
    "долгівець": "Duty member",
    "Свободовцы": "Freedom members",
}
